language: node_js

node_js: "lts/*"

os:
  - linux
  - osx

cache:
  yarn: true
  directories:
    - "node_modules"

before_install:
  - npm i -g yarn

script:
  - yarn lint
  #- yarn test-examples
  - yarn test-mul-nr
  - yarn test-examples
  - yarn nyct

after_success:
  - chmod 0755 /home/travis/build/l3laze/node-steam-config/.nyc_output
  - yarn textcov
  - yarn codecov

notifications:
  email: false
